apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myalpine
  name: myalpine
spec:
  containers:
  - image: alpine
    name: myalpine
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
