apiVersion: v1
kind: ReplicationController 
metadata:
  name: nginx-webserver
  labels:
    app: nginx-webserver

spec:
  template:
    metadata: 
      name: nginx-webserver
      labels:
        app: nginx-webserver

    spec:
      containers:
      - name: nginx
        image: nginx